apiVersion: v1
kind: Service
metadata:
  name: kub-crossnetwork-service-auth
spec:
  selector:
    name: auth-container
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: auth-container
  template:
    metadata:
      labels:
        name: auth-container
        type: auth
    spec:
      containers:
        - name: auth-container
          image: shahabu/kube-crossnetworking-auth:latest