apiVersion: v1
kind: Service
metadata:
  name: kube-crossnetworking-service-task
spec:
  selector:
    name: task-container
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-crossnetworking-task
spec:
  replicas: 1
  selector:
    matchLabels:
      name: task-container
  template:
    metadata: 
      labels: 
        name: task-container
        type: task
    spec:
      containers:
        - name: task-container
          image: shahabu/kube-crossnetworking-task:latest
          env:
            - name: TASKS_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: user-pod-env
                  key: TASK_FOLDER
            - name: AUTH_ADDRESS
              valueFrom:
                configMapKeyRef: 
                  name: user-pod-env
                  key: AUTH_ADDRESS
